### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/gltf-pipeline#1]
- [x] Stage to quantize vertices to use fewer bits using [WEB3D_quantized_attributes](https://github.com/KhronosGroup/glTF/blob/master/extensions/Vendor/WEB3D_quantized_attributes/README.md)
- [x] Stage to prebake AO
- [ ] Command-line and JSON input, e.g., like pdal (see [here](http://www.pdal.io/apps.html) and [here](http://www.pdal.io/pipeline.html))
- [x] Option to output separate resources (e.g., images) when writing out binary glTF
- [ ] Stage to minify JSON and GLSL, details: https://github.com/KhronosGroup/glTF/issues/35 and https://github.com/KhronosGroup/glTF/issues/36
- [x] Stage for pre and post vertex cache optimization.  Use Cesium's [implementation](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Tipsify.js).
- [x] Stage for oct encoding, see [AttributeCompression.octEncode](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/AttributeCompression.js#L43)
- [x] Stage to remove duplicate (property-wise) techniques/materials.
- [x] Stage to remove/merge duplicate vertices, https://github.com/KhronosGroup/glTF/issues/177
- [x] Stage to convert glTF 1.0 to 1.1, https://github.com/KhronosGroup/glTF/issues/605
- [ ] Stages from FBX2glTF.  See [Slide 5](https://www.khronos.org/assets/uploads/developers/library/2016-siggraph/glTF-MobileVR-Oculus-BOF-Update-SIGGRAPH_Jul16.pdf) from SIGGRAPH 2016
- [ ] Stage to compress textures, see http://gpuopen.com/compressonator-is-going-open-source/
- [ ] Stage to create texture atlases
- [x] Stage to replace [gltf-statistics](https://github.com/AnalyticalGraphicsInc/gltf-statistics)?
- [ ] Stage to interleave vertex attributes, https://github.com/KhronosGroup/glTF/issues/21
- [ ] Investigate GLSL optimizer, https://github.com/KhronosGroup/glTF/issues/34
- [ ] Stage to limit number of joints influencing a vertex, https://github.com/KhronosGroup/glTF/issues/203
- [x] Stage to generate normals if they are missing.
- [ ] Stage to support normal mapping. This can use Cesium's geometry pipeline to generate binormals and tangents.
- [ ] AO improvements, #125 
- [ ] Cleanup, #130 

**@leerichard42**
- [x] Stage to remove unused objects:
  - [x] Execute these in the right order, and add a test case that removes an unused node, which then causes other newly unused objects down the hierarchy to be removed
  - [x] `accessor`
  - [x] `buffer`
  - [x] `bufferView`
  - [x] `camera`
  - [x] `image`
  - [x] `material`
  - [x] `mesh`
  - [x] `node`
  - [x] `program`
  - [x] `sampler`
  - [x] `shader`
  - [x] `skin`
  - [x] `technique`
  - [x] `texture`
- [x] Stage to convert glTF with separate resources to glTF with embedded resources
  - [x] Update [obj2gltf](https://github.com/AnalyticalGraphicsInc/OBJ2GLTF) to use this.
  - [x] Stage to go in the reverse order
- [x] Stage to convert glTF to [binary glTF](https://github.com/KhronosGroup/glTF/blob/master/extensions/Khronos/KHR_binary_glTF/README.md) (also see [binary-gltf-utils](https://github.com/Qantas94Heavy/binary-gltf-utils))
  - [x] Stage to go in the reverse order
- [x] Stage to convert DAG to a tree, #40
- [x] Stage to remove unused vertices
- [x] Stage to combine primitives in a node, #43
- [x] Stage to combine nodes (that are not targeted for animation), https://github.com/KhronosGroup/glTF/issues/20, #43

**@pjcozzi**
- [x] Set up command-line tool, tests, jshint, etc.
- [x] Add third-party licenses to LICENSE.md
- [x] Set up coverage
- [x] Set up browserify
- [x] Stage to add defaults.  Replace [gltfDefaults](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/ThirdParty/gltfDefaults.js) in Cesium.
  - [x] Separate glTF 0.8 to 1.0 into another stage
  - [x] Separate materials extension?
- [x] Stage to generate shaders/techniques/materials from [KHR_materials_common](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common). Move `modelMaterialsCommon` from [obj2gltf](https://github.com/AnalyticalGraphicsInc/OBJ2GLTF) and [Cesium](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/modelMaterialsCommon.js) to here.
  - [x] Update obj2gltf and Cesium to use gltf-pipeline via npm and browserify.
- [ ] Streamline use of Cesium npm module, https://github.com/AnalyticalGraphicsInc/cesium/issues/2524.
- [x] Figure out in-memory representation so each stage doesn't have to write to and read from disk
- [x] Run jasmine and istanbul through gulp and karma
- [x] Reference doc
- [x] Publish to npm
- [ ] Consider using ES6 features with Node 4. https://github.com/bevacqua/es6

**Comment by pjcozzi** [comment]
@leerichard42 do you want to finish up the semester by implementing this optimization:

> [ ] Stage to remove unused vertices

We can generalize it a bit to remove empty parts of buffers in general.

**Comment by leerichard42** [comment]
Yes, sounds good! What exactly does it mean for a vertex to be unused/what is an empty part of a buffer? Would this consist of checking the sections of a buffer that are referenced by buffer views, and removing the sections which are not accessed?

**Comment by pjcozzi** [comment]
Exactly, I think all we need to do is once the pipeline stages to remove unused buffer views, accessors, etc. are ran, we just look for parts of buffers that are not referenced by buffer views, compact them, then update the buffer views.

@tfili do you have any other advice here?

**Comment by tfili** [comment]
You would be surprised how often you end up with vertex data that is never referenced by the indices. It must just be crappy exporters. Although rare, I've seen it where hundreds or thousands of vertices were removed. Normally it is just a few.

**Comment by pjcozzi** [comment]
Ah right, good call @tfili!  So @leerichard42 you'll have to check all the indices to see what parts of buffer views aren't used as well.  If it is cleaner, this could be two separate stages.

**Comment by pjcozzi** [comment]
> * [ ] Stage to remove duplicate (property-wise) techniques/materials.

Is this done?

**Comment by lasalvavida** [comment]
#152 will do that, but I'd prefer to get #157 in first.

**Comment by capitalknew** [comment]
I very waiting interleaving attributes support.

**Comment by ggetz** [comment]
@lilleyse @pjcozzi Good to close? Do we want to split any of the remaining items into their won issues?

**Comment by lilleyse** [comment]
Should be fine to close. Some of the items have been completed and others are probably out of scope now.
