### ISSUE TITLE
AO Roadmap

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/gltf-pipeline#125]
* [ ] Experiment to determine well-balanced settings for baking building AO
* [ ] Decouple uniform grid cell size from maximum ray distance
- treat the grid as a sparse voxel structure, rasterize rays in 3D and check for intersections along the line of voxels?
- use a different datastructure, like an oct tree?
* [ ] For baking to vertices: assess and document payload improvements of quantization
* [ ] For baking to vertices: assess ways to reduce the number of attributes and varyings that need to be added to shaders
- for AO on a diffuse texture, detect and use any existing `TEX_COORD` instead of a new `varying`
- detect places AO can be packed in other attributes (`VEC4` positions, `VEC3/VEC4` normals)
* [ ] For baking to textures: use [conservative rasterization](http://http.developer.nvidia.com/GPUGems2/gpugems2_chapter42.html) when sampling over triangles
* [ ] For baking to textures: Add a stage to generate texture coordinates
- possibly, unique AO texture coordinates with separate AO textures
- also requires shader modification for texture baking
* [ ] For baking to vertices: assess advanced baking approximations like [least squares baking](https://www.cs.utah.edu/~ladislav/kavan11least/kavan11least.pdf)
