### ISSUE TITLE
Texture Compression Roadmap

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/gltf-pipeline#210]
* [ ] Support mip-mapping? Cesium implementation does not yet (https://github.com/AnalyticalGraphicsInc/cesium/pull/4758)
* [ ] Do we want to support sRGB formats?
* [ ] Support loading target/dds/ktx as input images?
* [ ] Detect normal maps in some way. Some tools have special settings for these.
* [ ] Is it better to scale to the lower power-of-two or high power-of-two. Right now it scales to lower.
* [ ] HDR support - astc format supports this
* [ ] Is there a good place to put source code from the converter tools? Some tools have different mac/linux forks.
* [ ] Support uncompressed formats like RGB8 and RGBA8?
* [ ] Support for EAC formats or not a priority?
* [ ] For crunch do more verification: width, height, and expectedFormat - this requires a .crn reader
* [ ] Add a pipeline option for CPU core count for texture compression

Initial implementation: #204

**Comment by ggetz** [comment]
@lilleyse Should we close? See https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/330#issuecomment-384291705

**Comment by lilleyse** [comment]
Yes, closed.
